config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #resources :brands, only: [:index, :show] do
   scope  "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
       resources :car, :user
   end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord

  validates :name, presence: true

  belongs_to :user

  def user_text
    return self.user.name if self.user
  end

  def as_json(options={})
    options[:methods] = [:user_text]
    super
  end

end

app/models/user.rb
class User < ApplicationRecord

has_many :car
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/car_controller.rb
class CarController < ApplicationController

    before_action :set_locale

    def index
     @oResults=Car.all
    end

    def new
    end


    def create
        @car = Car.create(post_params)

          if @car.valid?

             ActionCable.server.broadcast "car_channel", message: @car.to_json
             redirect_to action: "index"
          else
            render :new
          end
    end


    def show

          @car = Car.find(params[:id])
    end

    def edit

          @car = Car.find(params[:id])
    end

    def update

          @car = Car.find(params[:id])
          if @car.update_attributes(post_params)
            redirect_to action: "index"
          else
            render :edit
          end

    end


    def destroy
       Car.find(params[:id]).delete
       redirect_to action: "index"
    end



    def post_params
      params.permit(:name,:user_id)
    end


    def set_locale
      I18n.locale = params[:locale] || I18n.default_locale
    end

end

app/controllers/user_controller.rb
require "kafka"
require "kafka/datadog"


class UserController < ApplicationController


  before_action :set_locale


  #layout "public", :only => [ :index, :show ]


  def index

    #
    ## Default is "127.0.0.1".
    # Kafka::Datadog.host = "127.0.0.1"
    #
    ##Default is 8125.
    # Kafka::Datadog.port = 8125
    #
    # Kafka::Datadog.namespace = "custom-namespace"




    # kafka = Kafka.new([ "localhost:9092"], client_id: "my-application")
    # kafka.deliver_message(" Hello, World!", topic: "greetings")





    #
    # kafka.each_message(topic: "greetings") do |message|
    #  puts message.offset, message.key, message.value
    # end



    @oResults=User.all
  end

  def new

  end


  def create
    @user = User.create(post_params)

    if @user.valid?
      redirect_to action: "index"
    else
      render :new
    end
  end


  def show

    @user = User.find(params[:id])
  end

  def edit

    @user = User.find(params[:id])
  end

  def update

    @user = User.find(params[:id])
    if @user.update_attributes(post_params)
      redirect_to action: "index"
    else
      render :edit
    end

  end


  def destroy
    User.find(params[:id]).delete
    redirect_to action: "index"
  end



  def post_params
    params.permit(:name,:email)
  end

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
    # I18n.default_locale= :ar
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/car_helper.rb
module CarHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/car/edit.html.erb
<% content_for :title do %>
 <%= t :edit %>
<% end %>






    <div id="page-wrapper">
        <div class="container-fluid">
            <!-- .row -->
            <div class="row bg-title" style="background:url(/images/top_banner.jpg) no-repeat center center /cover;">
                <div class="col-lg-12">
                    <h4 class="page-title"><%= t :edit %></h4>
                </div>
                <div class="col-sm-6 col-md-6 col-xs-12">
                    <ol class="breadcrumb pull-left">
                        <li><a href="#"><%= t :edit %></a></li>
                        <li class="active"><%= t :edit %></li>
                    </ol>
                </div>
                <div class="col-sm-6 col-md-6 col-xs-12">
                    <form role="search" method="get" action="" class="app-search hidden-xs pull-right">
                        <input type="text" placeholder=" {{ trans('general.search') }} ..." class="form-control">
                        <a href="javascript:void(0)"><i class="fa fa-search"></i></a>
                    </form>
                </div>
            </div>












            <div class="row">


                <div class="col-xs-12">
                    <div class="white-box">
                        <h3 class="box-title m-b-0"><%= t :edit %></h3>
                        <p class="text-muted m-b-40"><%= t :edit %></p>
                        <!-- Nav tabs -->


                        <ul class="nav nav-tabs" role="tablist">


                            <li role="presentation" class="active">
                                <a href="#idetail" aria-controls="detail" role="tab" data-toggle="tab" aria-expanded="true"><span><i class="ti-home"></i><%= t :basic %></span></a>
                            </li>



                        </ul>
                        <!-- Tab panes -->
                        <div class="tab-content">


                            <div role="tabpanel" class="tab-pane active" id="idetail">

<%= form_tag(car_path(I18n.locale,@car.id), method: "patch",class: "form-horizontal") do %>




                                <div class="panel">
                                    <div class="panel-heading">
                                        <span class="panel-title"><%= t :edit %></span>
                                    </div>

                                    <div class="panel-body">




                                        <div class="row">
                                        <div class="form-group <%  if @car && @car.errors.has_key?(:name) %> has-error <% end %>  col-xs-6">

                                            <%= label_tag(:name,"name",class: "col-sm-4 control-label") %>
                                            <div class="col-sm-8">

                                              <%= text_field_tag(:name ,@car.name,class: 'form-control') %>

                                              <%  if @car && @car.errors.has_key?(:name) %><p class="help-block"><%=@car.errors[:name].first() %></p><% end %>
                                            </div>
                                        </div>










                                        <div class="form-group">
                                            <div class="col-sm-offset-9 col-sm-3">
                                            <input name="user_id" value="<%= @car.user_id %>" type="hidden">
                                                <%= submit_tag("Save",class: 'btn btn-primary form-control') %>
                                            </div>
                                        </div>

                                    </div>
                                </div>
                        <% end %>


                            </div>

                        </div>
                    </div>
                </div>

            </div>







        </div>
    </div>

app/views/car/index.html.erb
<% content_for :title do %>
  <%= t :last_name %>
<% end %>






<div id="page-wrapper">
  <div class="container-fluid">
    <!-- .row -->
    <div class="row bg-title" style="background:url(/images/top_banner.jpg) no-repeat center center /cover;">
      <div class="col-lg-12">
        <h4 class="page-title"><%= t :car %></h4>
      </div>
      <div class="col-sm-6 col-md-6 col-xs-12">
        <ol class="breadcrumb pull-left">
          <li><a href="#"><%= t :car %></a></li>

        </ol>
      </div>
      <div class="col-sm-6 col-md-6 col-xs-12">
        <form role="search" class="app-search hidden-xs pull-right">
          <input type="text" placeholder=" {{ trans('general.search') }} ..." class="form-control">
          <a href="javascript:void(0)"><i class="fa fa-search"></i></a>
        </form>
      </div>
    </div>

    <div class="row">
      <div class="col-lg-12">
        <div class="white-box">




          <div class=" col-xs-9">
            <h3 class="box-title m-b-0"><%= t :areaTableHead %></h3>
            <p class="text-muted m-b-20"><%= t :areaTableDescription %></p>



          </div>
          <div class="col-xs-3">
            <a  href="/<%=I18n.locale %><%= new_car_path %>"class="btn btn-primary form-control">
              + <%= t :create %>

            </a>
          </div>

          <table id="main_car_table" class="tablesaw table-bordered table-hover table" data-tablesaw-mode="swipe" data-tablesaw-sortable data-tablesaw-sortable-switch data-tablesaw-minimap data-tablesaw-mode-switch>

            <thead>
            <tr>


              <th scope="col" data-tablesaw-sortable-col data-tablesaw-priority="1">
                id
              </th>

              <th scope="col" data-tablesaw-sortable-col data-tablesaw-priority="2">
                name
              </th>
              <th scope="col" data-tablesaw-sortable-col data-tablesaw-priority="2">
                user
              </th>


              <th class="actionHeader"><i class="fa fa-cog"></i> </th>

            </tr>
            </thead>
            <tbody>

            <% @oResults.each do |oResult| %>
              <tr class='{{ $class }}'>


                <td><%=oResult.id %></td>
                <td><%=oResult.name %></td>
                <td><%=oResult.user_text %></td>


                <td>

                  <div class="tableActionsMenuDiv">
                    <div class="innerContainer">
                      <i class="fa fa-list menuIconList"></i>





                      <%= form_tag(car_path(I18n.locale,oResult.id), method: "delete") do %>
                        <button type="submit" name="Delete" class="deleteRow" >
                          <i class="fa fa-trash"></i>
                        </button>
                      <% end %>


                      <a href="<%= edit_car_path(I18n.locale,oResult.id) %>"
                         class="fa fa-edit"></a>

                      <a href="<%= car_path(I18n.locale,oResult.id) %>"
                         class="fa fa-file-text"></a>


                    </div>
                  </div>
                </td>
              </tr>
            <% end %>




            </tbody>
          </table>

        </div>
      </div>
    </div>
    <!-- /.container-fluid -->
    <footer class="footer text-center"> <%= t :CopyRights %> </footer>
  </div>
  <!-- /#page-wrapper -->
  <!-- .right panel -->
  <div class="right-side-panel">
    <div class="scrollable-right container">
      <!-- .Theme settings -->
      <h3 class="title-heading"><%= t :search %></h3>

      {!! Form::model($request,['method'=>'get','id'=>'searchForm', 'class'=>'form-horizontal']) !!}






      <div class="form-group">
        <div class="col-md-12">
          id
        </div>
      </div>



      <div class="form-group">
        <div class="col-md-12">
          name
        </div>
      </div>











      <div class="form-group">
        <label class="col-md-12"></label>
        <div class="col-md-12">
          {!! Form::submit(trans('general.search'), ['class'=>'btn btn-info btn-sm', 'name' => 'search']) !!}
        </div>
      </div>

      {!! Form::hidden('sort', null) !!}
      {!! Form::hidden('order', null) !!}
      {!! Form::close()!!}
    </div>
  </div>

app/views/car/new.html.erb
<% content_for :title do %>
 <%= t :create %>
<% end %>






    <div id="page-wrapper">
        <div class="container-fluid">
            <!-- .row -->
            <div class="row bg-title" style="background:url(/images/top_banner.jpg) no-repeat center center /cover;">
                <div class="col-lg-12">
                    <h4 class="page-title"><%= t :create %></h4>
                </div>
                <div class="col-sm-6 col-md-6 col-xs-12">
                    <ol class="breadcrumb pull-left">
                        <li><a href="#"><%= t :create %></a></li>
                        <li class="active"><%= t :create %></li>
                    </ol>
                </div>
                <div class="col-sm-6 col-md-6 col-xs-12">
                    <form role="search" method="get" action="" class="app-search hidden-xs pull-right">
                        <input type="text" placeholder=" {{ trans('general.search') }} ..." class="form-control">
                        <a href="javascript:void(0)"><i class="fa fa-search"></i></a>
                    </form>
                </div>
            </div>












            <div class="row">


                <div class="col-xs-12">
                    <div class="white-box">
                        <h3 class="box-title m-b-0"><%= t :create %></h3>
                        <p class="text-muted m-b-40"><%= t :create %></p>
                        <!-- Nav tabs -->


                        <ul class="nav nav-tabs" role="tablist">


                            <li role="presentation" class="active">
                                <a href="#idetail" aria-controls="detail" role="tab" data-toggle="tab" aria-expanded="true"><span><i class="ti-home"></i><%= t :basic %></span></a>
                            </li>



                        </ul>
                        <!-- Tab panes -->
                        <div class="tab-content">


                            <div role="tabpanel" class="tab-pane active" id="idetail">

<%= form_tag( "/car", method: "post",class: "form-horizontal") do %>




                                <div class="panel">
                                    <div class="panel-heading">
                                        <span class="panel-title"><%= t :create %></span>
                                    </div>

                                    <div class="panel-body">




                                        <div class="row">
                                        <div class="form-group <%  if @car && @car.errors.has_key?(:name) %> has-error <% end %>  col-xs-6">

                                            <%= label_tag(:name,"name",class: "col-sm-4 control-label") %>
                                            <div class="col-sm-8">

                                              <%= text_field_tag(:name ,"",class: 'form-control') %>

                                              <%  if @car && @car.errors.has_key?(:name) %><p class="help-block"><%=@car.errors[:name].first() %></p><% end %>
                                            </div>
                                        </div>










                                        <div class="form-group">
                                            <div class="col-sm-offset-9 col-sm-3">
                                            <input name="user_id" value="1" type="hidden">
                                                <%= submit_tag("Save",class: 'btn btn-primary form-control') %>
                                            </div>
                                        </div>

                                    </div>
                                </div>
                        <% end %>


                            </div>

                        </div>
                    </div>
                </div>

            </div>







        </div>
    </div>

app/views/car/show.html.erb
<% content_for :title do %>
 <%= t :show %>
<% end %>






    <div id="page-wrapper">
        <div class="container-fluid">
            <!-- .row -->
            <div class="row bg-title" style="background:url(/images/top_banner.jpg) no-repeat center center /cover;">
                <div class="col-lg-12">
                    <h4 class="page-title"><%= t :show %></h4>
                </div>
                <div class="col-sm-6 col-md-6 col-xs-12">
                    <ol class="breadcrumb pull-left">
                        <li><a href="#"><%= t :show %></a></li>
                        <li class="active"><%= t :show %></li>
                    </ol>
                </div>
                <div class="col-sm-6 col-md-6 col-xs-12">
                    <form role="search" method="get" action="" class="app-search hidden-xs pull-right">
                        <input type="text" placeholder=" {{ trans('general.search') }} ..." class="form-control">
                        <a href="javascript:void(0)"><i class="fa fa-search"></i></a>
                    </form>
                </div>
            </div>












            <div class="row">


                <div class="col-xs-12">
                    <div class="white-box">
                        <h3 class="box-title m-b-0"><%= t :show %></h3>
                        <p class="text-muted m-b-40"><%= t :show %></p>
                        <!-- Nav tabs -->


                        <ul class="nav nav-tabs" role="tablist">


                            <li role="presentation" class="active">
                                <a href="#idetail" aria-controls="detail" role="tab" data-toggle="tab" aria-expanded="true"><span><i class="ti-home"></i><%= t :basic %></span></a>
                            </li>



                        </ul>
                        <!-- Tab panes -->
                        <div class="tab-content">


                            <div role="tabpanel" class="tab-pane active" id="idetail">




                                <div class="panel">
                                    <div class="panel-heading">
                                        <span class="panel-title"><%= t :show %></span>
                                    </div>

                                    <div class="panel-body">




                                        <div class="row">
                                        


                                        <div class="col-sm-2 text-right">
                                                <div class="form-group no-margin-hr">
                                                    <label class="control-label"><%= t :name %> </label>
                                                </div>
                                            </div>


                                            <div class="col-sm-4 text-left">
                                                <div class="form-group no-margin-hr">
                                                    <label class="control-label">
                                                    <%= @car.name %>
                                                    </label>
                                                </div>
                                            </div>











                                    </div>
                                </div>


                            </div>

                        </div>
                    </div>
                </div>

            </div>







        </div>
    </div>

app/views/layouts/partial/_header.html.erb
  <!-- Top Navigation -->
  <nav class=" navbar navbar-default navbar-static-top m-b-0"  >
    <div class="navbar-header">
      <!-- .Logo -->
      <div class="top-left-part"><a class="logo" href="/admin/dashboard">
        <!--This is logo icon-->


        <img src="/images/shopify_small_logo.png" alt="home" class="light-logo" style="width:47px;height:56px;display:block;" /></a></div>
         <ul class="nav navbar-top-links navbar-left hidden-xs">
           <li><a href="javascript:void(0)" class="logotext">
             <!--This is logo text-->
             <img src="/images/logo_full.png" style="max-width:100px;" alt="home" class="light-logo" alt="home" /></a></li>
         </ul>
      <!-- /.Logo -->
      <!-- top right panel -->
      <ul class="nav navbar-top-links navbar-right pull-right">















        <!-- .dropdown -->
        <li class="dropdown">
         <a class="dropdown-toggle waves-effect waves-light" data-toggle="dropdown" href="#"><i class="fa fa-language"></i>
<%= t :language  %>
          </a>
          <ul class="dropdown-menu dropdown-tasks animated slideInUp">



                </ul>
          <!-- /.dropdown-tasks -->
        </li>
        <!-- /.dropdown -->
        <!-- .dropdown -->
        <li class="dropdown"> <a class="dropdown-toggle profile-pic" data-toggle="dropdown" href="#"> <img src="/images/user_image.jpg" alt="user-img" width="36" class="img-circle"><b class="hidden-xs"> User</b> </a>
          <ul class="dropdown-menu dropdown-user animated flipInY">

           <li role="separator" class="divider"></li>
                            <li><a href=" {{ route('admin.logout') }}"><i class="fa fa-power-off"></i><%= t :logout %></a></li>
                                                          </ul>
                                                          <!-- /.dropdown-user -->
                                                        </li>
                                                        <!-- /.dropdown -->
                                                        <!-- .right toggle -->
                                                        <li class="right-side-toggle"><a class="waves-effect waves-light" href="javascript:void(0)"> <i class="ti-arrow-right"></i></a></li>
                                                        <!-- /.right toggle -->
                                                      </ul>
                                                      <!-- top right panel -->
                                                    </div>
                                                  </nav>
                                                  <!-- End Top Navigation -->

app/views/layouts/partial/_message.html.erb
<% if @car && @car.errors.any?
  @car.errors.each do |attribute, message|  %>
<%= attribute %>
<%=message %>
<% end
   end %>

app/views/layouts/public.html.erb
dvvvvvv

app/views/user/edit.html.erb
<% content_for :title do %>
 <%= t :edit %>
<% end %>






    <div id="page-wrapper">
        <div class="container-fluid">
            <!-- .row -->
            <div class="row bg-title" style="background:url(/images/top_banner.jpg) no-repeat center center /cover;">
                <div class="col-lg-12">
                    <h4 class="page-title"><%= t :edit %></h4>
                </div>
                <div class="col-sm-6 col-md-6 col-xs-12">
                    <ol class="breadcrumb pull-left">
                        <li><a href="#"><%= t :edit %></a></li>
                        <li class="active"><%= t :edit %></li>
                    </ol>
                </div>
                <div class="col-sm-6 col-md-6 col-xs-12">
                    <form role="search" method="get" action="" class="app-search hidden-xs pull-right">
                        <input type="text" placeholder=" {{ trans('general.search') }} ..." class="form-control">
                        <a href="javascript:void(0)"><i class="fa fa-search"></i></a>
                    </form>
                </div>
            </div>












            <div class="row">


                <div class="col-xs-12">
                    <div class="white-box">
                        <h3 class="box-title m-b-0"><%= t :edit %></h3>
                        <p class="text-muted m-b-40"><%= t :edit %></p>
                        <!-- Nav tabs -->


                        <ul class="nav nav-tabs" role="tablist">


                            <li role="presentation" class="active">
                                <a href="#idetail" aria-controls="detail" role="tab" data-toggle="tab" aria-expanded="true"><span><i class="ti-home"></i><%= t :basic %></span></a>
                            </li>



                        </ul>
                        <!-- Tab panes -->
                        <div class="tab-content">


                            <div role="tabpanel" class="tab-pane active" id="idetail">

<%= form_tag(user_path(I18n.locale,@user.id), method: "patch",class: "form-horizontal") do %>




                                <div class="panel">
                                    <div class="panel-heading">
                                        <span class="panel-title"><%= t :edit %></span>
                                    </div>

                                    <div class="panel-body">




                                        <div class="row">
                                        <div class="form-group <%  if @user && @user.errors.has_key?(:name) %> has-error <% end %>  col-xs-6">

                                            <%= label_tag(:name,"name",class: "col-sm-4 control-label") %>
                                            <div class="col-sm-8">

                                              <%= text_field_tag(:name ,@user.name,class: 'form-control') %>

                                              <%  if @user && @user.errors.has_key?(:name) %><p class="help-block"><%=@user.errors[:name].first() %></p><% end %>
                                            </div>
                                        </div>










                                        <div class="form-group">
                                            <div class="col-sm-offset-9 col-sm-3">
                                                <%= submit_tag("Save",class: 'btn btn-primary form-control') %>
                                            </div>
                                        </div>

                                    </div>
                                </div>
                        <% end %>


                            </div>

                        </div>
                    </div>
                </div>

            </div>







        </div>
    </div>

app/views/user/index.html.erb
<% content_for :title do %>
 <%= t :last_name %>
<% end %>






   <div id="page-wrapper">
        <div class="container-fluid">
            <!-- .row -->
            <div class="row bg-title" style="background:url(/images/top_banner.jpg) no-repeat center center /cover;">
                <div class="col-lg-12">
                    <h4 class="page-title"><%= t :user %></h4>
                </div>
                <div class="col-sm-6 col-md-6 col-xs-12">
                    <ol class="breadcrumb pull-left">
                        <li><a href="#"><%= t :user %></a></li>

                    </ol>
                </div>
                <div class="col-sm-6 col-md-6 col-xs-12">
                    <form role="search" class="app-search hidden-xs pull-right">
                        <input type="text" placeholder=" {{ trans('general.search') }} ..." class="form-control">
                        <a href="javascript:void(0)"><i class="fa fa-search"></i></a>
                    </form>
                </div>
            </div>

            <div class="row">
                <div class="col-lg-12">
                    <div class="white-box">




                        <div class=" col-xs-9">
                            <h3 class="box-title m-b-0"><%= t :areaTableHead %></h3>
                            <p class="text-muted m-b-20"><%= t :areaTableDescription %></p>



                        </div>
                        <div class="col-xs-3">
                            <a  href="/<%=I18n.locale %><%= new_user_path %>"class="btn btn-primary form-control">
                                + <%= t :create %>

                            </a>
                        </div>

                        <table class="tablesaw table-bordered table-hover table" data-tablesaw-mode="swipe" data-tablesaw-sortable data-tablesaw-sortable-switch data-tablesaw-minimap data-tablesaw-mode-switch>

                            <thead>
                            <tr>


                                                                    <th scope="col" data-tablesaw-sortable-col data-tablesaw-priority="1">
                                      id
                                    </th>

                                                                    <th scope="col" data-tablesaw-sortable-col data-tablesaw-priority="2">
                                       name
                                        </th>


                                    <th class="actionHeader"><i class="fa fa-cog"></i> </th>

                            </tr>
                            </thead>
                            <tbody>

                               <% @oResults.each do |oResult| %>
                                                                 <tr class='{{ $class }}'>


                                                                                <td><%=oResult.id %></td>
                                                                                <td><%=oResult.name %></td>


                                        <td>

                                            <div class="tableActionsMenuDiv">
                                                <div class="innerContainer">
                                                    <i class="fa fa-list menuIconList"></i>





                                                    <%= form_tag(user_path(I18n.locale,oResult.id), method: "delete") do %>
 <button type="submit" name="Delete" class="deleteRow" >
                                                        <i class="fa fa-trash"></i>
                                                    </button>
<% end %>


                                            <a href="<%= edit_user_path(I18n.locale,oResult.id) %>"
                                               class="fa fa-edit"></a>

                                                    <a href="<%= user_path(I18n.locale,oResult.id) %>"
                                                       class="fa fa-file-text"></a>


                                                </div>
                                                </div>
                                        </td>
                                    </tr>
                               <% end %>




                            </tbody>
                        </table>

                    </div>
                </div>
            </div>
            <!-- /.container-fluid -->
            <footer class="footer text-center"> <%= t :CopyRights %> </footer>
        </div>
        <!-- /#page-wrapper -->
        <!-- .right panel -->
        <div class="right-side-panel">
            <div class="scrollable-right container">
                <!-- .Theme settings -->
                <h3 class="title-heading"><%= t :search %></h3>

                {!! Form::model($request,['method'=>'get','id'=>'searchForm', 'class'=>'form-horizontal']) !!}






                <div class="form-group">
                    <div class="col-md-12">
                       id
                    </div>
                </div>



                <div class="form-group">
                    <div class="col-md-12">
                   name
                    </div>
                </div>











                <div class="form-group">
                    <label class="col-md-12"></label>
                    <div class="col-md-12">
                        {!! Form::submit(trans('general.search'), ['class'=>'btn btn-info btn-sm', 'name' => 'search']) !!}
                    </div>
                </div>

                {!! Form::hidden('sort', null) !!}
                {!! Form::hidden('order', null) !!}
                {!! Form::close()!!}
            </div>
        </div>